package:
    name:           hipanel-module-dns
    label:          HipanelModuleDns
    title:          Hipanel Module Dns
    type:           package
    keywords:       hipanel, module, dns
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
