package:
    type:           yii2-extension
    name:           hipanel-module-dns
    namespace:      hipanel\modules\dns
    label:          HiPanel DNS
    title:          HiPanel DNS Module
    keywords:       hipanel, module, dns

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
