package:
    name:           hipanel-module-dns
    namespace:      hipanel\modules\dns
    label:          HipanelModuleDns
    title:          Hipanel Module Dns
    type:           yii2-extension
    keywords:       hipanel, module, dns
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
